server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_demo
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.jtl.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1